# Generated by Django 5.1.7 on 2025-03-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('idAlumnes', models.AutoField(primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=255, verbose_name='nomComplet')),
                ('img', models.CharField(max_length=255, verbose_name='img')),
                ('questionari', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionari',
            fields=[
                ('idQuestionaris', models.AutoField(primary_key=True, serialize=False)),
                ('idEmpresa', models.IntegerField(verbose_name='idEmpresa')),
                ('descripcio', models.CharField(max_length=255, verbose_name='descripcio')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRols', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunte',
            fields=[
                ('idPreguntes', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.CharField(max_length=255, verbose_name='descripcio')),
                ('questionari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquestes.questionari')),
            ],
        ),
    ]
