# Generated by Django 5.1.7 on 2025-03-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnes',
            fields=[
                ('idAlumnes', models.AutoField(primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=255, verbose_name='nomComplet')),
                ('img', models.CharField(max_length=255, verbose_name='img')),
                ('questionari', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaris',
            fields=[
                ('idQuestionaris', models.AutoField(primary_key=True, serialize=False)),
                ('idEmpresa', models.IntegerField(verbose_name='idEmpresa')),
                ('descripcio', models.CharField(max_length=255, verbose_name='descripcio')),
            ],
        ),
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('idRols', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.IntegerField(choices=[(0, 'Professor'), (1, 'Coordinador')])),
            ],
        ),
        migrations.CreateModel(
            name='Preguntes',
            fields=[
                ('idPreguntes', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.CharField(max_length=255, verbose_name='descripcio')),
                ('Questionari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquestes.questionaris')),
            ],
        ),
    ]
