# Generated by Django 5.1.7 on 2025-03-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquestes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntes',
            old_name='Questionari',
            new_name='questionari',
        ),
    ]
