# Generated by Django 5.1.7 on 2025-03-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquestes', '0002_rename_questionari_preguntes_questionari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rols',
            new_name='Rol',
        ),
    ]
