# Generated by Django 5.1.7 on 2025-03-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquestes', '0003_rename_rols_rol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnes',
            new_name='Alumne',
        ),
        migrations.RenameModel(
            old_name='Preguntes',
            new_name='Pregunte',
        ),
        migrations.RenameModel(
            old_name='Questionaris',
            new_name='Questionari',
        ),
    ]
