# Generated by Django 5.1.7 on 2025-03-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    def create_rols(apps, schema_editor):
        Rol = apps.get_model('Enquestes', 'Rol')
        Rol.objects.create(nom = 1)
        Rol = apps.get_model('Enquestes', 'Rol')
        Rol.objects.create(nom = 2)

    def create_questionari(apps, schema_editor):
        Questionari = apps.get_model('Enquestes', 'Questionari')
        Questionari.objects.create(idEmpresa = 1, descripcio = 'Qüestionari de prova')

    def create_alumne(apps, schema_editor):
        Alumne = apps.get_model('Enquestes', 'Alumne')
        Alumne.objects.create(nomComplet = 'Eloi', img = "", questionari = False)

    def create_pregunta(apps, schema_editor):
        Pregunta = apps.get_model('Enquestes', 'Pregunte')
        Pregunta.objects.create(descripcio = 'Pregunta de prova', questionari_id = 1)

    dependencies = [
        ('Enquestes', '0004_rename_alumnes_alumne_rename_preguntes_pregunte_and_more'),
    ]

    operations = [
        migrations.RunPython(create_rols),
        migrations.RunPython(create_questionari),
        migrations.RunPython(create_alumne),
        migrations.RunPython(create_pregunta)
    ]
